language: python

python:
  - "2.6"
  - "2.7"
  - "3.4"

install:
  - pip install pytest pylint==1.3.1 argh boto docutils genshi GitPython paramiko setuptools sphinx
  - "(python -V 2>&1 | grep -qF 'Python 3') || pip install cheetah"

script:
  - # Travis does a shallow clone and won't find tags with git describe
  - echo "__version__ = '0.8-travis'" > poni/version.py
  - make all rst2html=rst2html.py
  - "(python -V 2>&1 | grep -qF 'Python 2.6') || make pylint"
  - make tests

notifications:
  slack: ohmu:rihgYxa0c4dFiPvdAPAgP7R4
